"""Performance dashboard widget with auto-updating insights."""

from PySide6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QTextEdit, 
    QGroupBox, QGridLayout, QPushButton
)
from PySide6.QtCore import QTimer
import sqlite3
from pathlib import Path
from datetime import timedelta, datetime


class PerformanceDashboard(QWidget):
    """Auto-updating performance dashboard showing LLM analytics."""
    
    def __init__(self, parent=None):
        super().__init__(parent)
        self.db_path = Path("data/performance.db")
        self._setup_ui()
        
        # Auto-refresh every 30 seconds
        self.refresh_timer = QTimer()
        self.refresh_timer.timeout.connect(self.refresh_insights)
        self.refresh_timer.start(30000)
        
        # Initial load
        self.refresh_insights()
    
    def _setup_ui(self):
        """Set up the UI components."""
        layout = QVBoxLayout(self)
        layout.setContentsMargins(16, 16, 16, 16)
        layout.setSpacing(16)
        
        # Title
        title = QLabel("Performance Analytics")
        title.setStyleSheet("font-size: 14pt; font-weight: bold; color: #f4f4f5;")
        layout.addWidget(title)
        
        # Quick stats section
        stats_group = QGroupBox("Quick Stats (Last 7 Days)")
        stats_group.setStyleSheet("""
            QGroupBox {
                font-weight: 600;
                border: 1px solid #27272a;
                border-radius: 8px;
                margin-top: 8px;
                padding-top: 16px;
                background-color: #1a1a20;
            }
            QGroupBox::title {
                color: #a1a1aa;
                subcontrol-origin: margin;
                left: 12px;
                padding: 0 6px;
            }
        """)
        stats_layout = QGridLayout()
        stats_layout.setSpacing(16)
        
        self.stat_labels = {}
        stat_configs = [
            ("total_queries", "Total Queries"),
            ("avg_tps", "Avg Speed"),
            ("errors", "Errors"),
            ("models_used", "Models Used")
        ]
        
        for i, (key, name) in enumerate(stat_configs):
            label = QLabel(name + ":")
            label.setStyleSheet("font-weight: 600; color: #a1a1aa; font-size: 10pt;")
            
            value = QLabel("0")
            value.setStyleSheet("font-size: 20pt; font-weight: bold; color: #8b7cf6;")
            
            row = i // 2
            col = (i % 2) * 2
            
            stats_layout.addWidget(label, row, col)
            stats_layout.addWidget(value, row, col + 1)
            
            self.stat_labels[key] = value
        
        stats_group.setLayout(stats_layout)
        layout.addWidget(stats_group)
        
        # Latest insights section (auto-generated by Mistral Nemo)
        insights_group = QGroupBox("Latest Insights (Auto-Generated by Mistral Nemo 12B)")
        insights_group.setStyleSheet("""
            QGroupBox {
                font-weight: 600;
                border: 1px solid #27272a;
                border-radius: 8px;
                margin-top: 8px;
                padding-top: 16px;
                background-color: #1a1a20;
            }
            QGroupBox::title {
                color: #a1a1aa;
                subcontrol-origin: margin;
                left: 12px;
                padding: 0 6px;
            }
        """)
        insights_layout = QVBoxLayout()
        
        self.insights_text = QTextEdit()
        self.insights_text.setReadOnly(True)
        self.insights_text.setMinimumHeight(250)
        self.insights_text.setStyleSheet("""
            QTextEdit {
                background-color: #18181b;
                border: 1px solid #27272a;
                border-radius: 6px;
                padding: 12px;
                color: #e4e4e7;
                font-size: 10pt;
                line-height: 1.5;
            }
        """)
        insights_layout.addWidget(self.insights_text)
        
        # Timestamp and refresh button
        bottom_layout = QHBoxLayout()
        
        self.insights_timestamp = QLabel()
        self.insights_timestamp.setStyleSheet("color: #71717a; font-size: 9pt;")
        bottom_layout.addWidget(self.insights_timestamp)
        
        bottom_layout.addStretch()
        
        refresh_btn = QPushButton("Refresh Now")
        refresh_btn.setProperty("styleClass", "ghost")
        refresh_btn.clicked.connect(self.refresh_insights)
        refresh_btn.setStyleSheet("""
            QPushButton {
                padding: 6px 12px;
                border: 1px solid #3f3f46;
                border-radius: 4px;
                background-color: transparent;
                color: #a1a1aa;
            }
            QPushButton:hover {
                background-color: #27272a;
                border-color: #52525b;
            }
        """)
        bottom_layout.addWidget(refresh_btn)
        
        insights_layout.addLayout(bottom_layout)
        
        insights_group.setLayout(insights_layout)
        layout.addWidget(insights_group)
        
        layout.addStretch()
    
    def refresh_insights(self):
        """Load latest auto-generated insights and stats."""
        try:
            if not self.db_path.exists():
                self.insights_text.setPlainText(
                    "No performance data yet.\\n\\n"
                    "Run some queries with different models to generate automatic insights!"
                )
                return
            
            with sqlite3.connect(self.db_path) as conn:
                # Get latest insights
                result = conn.execute("""
                    SELECT content, generated_at 
                    FROM performance_insights 
                    ORDER BY generated_at DESC 
                    LIMIT 1
                """).fetchone()
                
                if result:
                    self.insights_text.setPlainText(result[0])
                    self.insights_timestamp.setText(f"Generated: {result[1]}")
                else:
                    total = conn.execute("SELECT COUNT(*) FROM llm_performance").fetchone()[0]
                    if total == 0:
                        self.insights_text.setPlainText(
                            "No queries logged yet.\\n\\n"
                            "Start using the application - insights will auto-generate after 10 queries!"
                        )
                    else:
                        self.insights_text.setPlainText(
                            f"Logged {total} queries so far.\\n\\n"
                            "Insights will auto-generate after 10 queries or 5 minutes."
                        )
                
                # Update quick stats
                cutoff = datetime.now() - timedelta(days=7)
                stats_result = conn.execute("""
                    SELECT 
                        COUNT(*) as total,
                        COUNT(DISTINCT model) as models,
                        AVG(tokens_per_second) as avg_tps,
                        SUM(CASE WHEN error IS NOT NULL THEN 1 ELSE 0 END) as errors
                    FROM llm_performance
                    WHERE timestamp > ?
                """, (cutoff,)).fetchone()
                
                if stats_result:
                    total, models, avg_tps, errors = stats_result
                    self.stat_labels["total_queries"].setText(str(total))
                    self.stat_labels["models_used"].setText(str(models))
                    self.stat_labels["avg_tps"].setText(f"{avg_tps:.1f} t/s" if avg_tps else "0 t/s")
                    self.stat_labels["errors"].setText(str(errors))
                    
        except Exception as e:
            print(f"[DASHBOARD ERROR] {e}")
            self.insights_text.setPlainText(f"Error loading insights: {e}")
